import { useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function FactoryModel({ showModal, handleMeshClick }) {
  const { nodes, materials } = useGLTF('./models/factory01.glb')

  const [hoverColor, setHoverColor] = useState();
  const [clickMesh, setClickMesh] = useState();

  const defaultColor = materials.project_initialShadingGroup2;
  const hoveredColor = defaultColor.clone();
  hoveredColor.color.set('#333');

  const onClickMesh = (info) => {
    handleMeshClick(info);
    setClickMesh(info);
  }

  useEffect(() => {
    if (showModal == false) {
      setClickMesh(null)
    }
  }, [showModal])

  const onMeshOver = (meshId) => {
    setHoverColor(meshId); // 현재 호버된 메쉬의 ID 저장
    console.log(meshId)
  };
  
  const onMeshOut = () => {
    setHoverColor(null); // 호버 상태 해제
  };

  const getColor = (meshId) => {
    if (clickMesh?.id === meshId) return hoveredColor; // 클릭된 메쉬일 때
    if (hoverColor === meshId) return hoveredColor; // 호버된 메쉬일 때
    return defaultColor; // 기본 재질
  };

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube16polySurface73_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.objWaterFi_project_lambert2SG1_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.objWaterFi1_project_lambert2SG1_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.objWaterFi2_project_lambert2SG1_0.geometry}
            onClick={() => onClickMesh({ name: nodes.objWaterFi2_project_lambert2SG1_0.name, text: '통3개'})}
            onPointerOver={() => onMeshOver(nodes.objWaterFi2_project_lambert2SG1_0.name)}
            onPointerOut={onMeshOut}
            material={getColor(nodes.objWaterFi2_project_lambert2SG1_0.name)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube24_project_initialShadingGroup2_0.geometry}
            material={materials.project_lambert2SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder31_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface22_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface25_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface26_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface26_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube003_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinde292_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube26_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface27_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder33_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder33_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder33_project_initialShadingGroup2_0_1.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinde293_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube004_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube005_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube006_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_1.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Turbina_N220908_Cylinder20_project_initialShadingGroup2_0_2.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Turbina_N220908_Cylinder20_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface36_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface36_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface18_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface18_project_lambert3SG1_0.geometry}
            material={materials.project_lambert3SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface18_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface47_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface47_project_lambert3SG1_0.geometry}
            material={materials.project_lambert3SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface47_project_lambert4SG1_0.geometry}
            material={materials.project_lambert4SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface48_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface48_project_lambert6SG1_0.geometry}
            material={materials.project_lambert6SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface48_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface48_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface20pCylinder9_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder9polySurface21_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder9polySurface23_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder9polySurface35_project_lambert3SG1_0.geometry}
            material={materials.project_lambert3SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder9polySurface45_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder9polySurface46_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface31polySurface29_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface29polySurface32_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface29polySurface33_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface29polySurface34_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0.geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_1
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.polySurface39Turbina_N220908_Cylinder19_project_initialShadingGroup2_0_2
                .geometry
            }
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface49polySurface42_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface50_project_lambert6SG1_0.geometry}
            material={materials.project_lambert6SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface51_project_lambert5SG1_0.geometry}
            material={materials.project_lambert5SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface52_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface53_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface54_project_blinn1SG1_0.geometry}
            material={materials.project_blinn1SG1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface55_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface42polySurface56_project_initialShadingGroup2_0.geometry}
            material={materials.project_initialShadingGroup2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/factory01.glb')